name: Run checks

on:
  pull_request:
    branches:
    - main

jobs:
  
  run-checks:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: run script
      run: ./scripts/run-checks.sh
